const Politicas = () => {

  return (
    <div>
      <div className="container-fluid">
        <div className="container politicas">
          <div className="row">
            <div className="col">
              <h1>Termos e Condições de Uso Lyndus</h1>
              <br/><br/>
              <p><b>O uso e acesso aos nossos serviços, definidos abaixo, estão sujeitos aos termos a seguir. Leia integralmente e com atenção estes termos de uso, pois constam deles todas as informações importantes sobre os seus direitos e obrigações legais para utilização dos serviços disponibilizados.  Caso não concorde com as disposições expostas, você não terá permissão para o uso e/ou acesso aos serviços da Lyndus.</b><br/><br/>
              Honrosamente damos a você as boas-vindas a um universo que faz bem, o universo Lyndus!<br/><br/>
              Leia este documento para compreender as regras e restrições que regem a utilização do aplicativo Lyndus, os serviços de empresas intermediárias fornecidos pela Lyndus e os produtos adicionais da Lyndus oferecidos dentro do aplicativo.<br/><br/>
              <li>Definições</li><br/>
              USUÁRIO – qualquer pessoa que acesse a plataforma Lyndus;<br/><br/>
              ENVIO DE USUÁRIO - Qualquer coisa que você postar, carregar, compartilhar, armazenar ou de outra forma disponibilizar por meio dos serviços (incluindo, sem limitação, imagens, avaliações, comentários e outros conteúdos que serão exibidos no aplicativo Lyndus) constitui o seu "Envio de Usuário";<br/><br/>
              DADO PESSOAL – informação relacionada a pessoa natural identificada ou identificável;<br/><br/>
              BANCO DE DADOS – conjunto estruturado de dados pessoais, estabelecido em um ou em vários locais, em suporte eletrônico ou físico;<br/><br/>
              TITULAR – pessoa natural a quem se referem os dados pessoais que são objeto de tratamento;<br/><br/>
              CONTROLADOR – Lyndus;<br/><br/>
              OPERADOR – pessoa responsável designada pela Lyndus para realizar o tratamento dos dados pessoais coletados em nome do controlador;<br/><br/>
              TRATAMENTO – toda operação realizada com dados pessoais, como as que se referem a coleta, produção, recepção, classificação, utilização, acesso, reprodução, transmissão, distribuição, processamento, arquivamento, armazenamento, eliminação, avaliação ou controle de informação, modificação, comunicação, transferência, difusão ou extração;<br/><br/>
              ELIMINAÇÃO – exclusão de dado ou conjunto de dados armazenados em banco de dados.<br/><br/>
              <li>A Lyndus</li><br/>
              A Lyndus é uma plataforma que atua como conectora entre salões de beleza, clínicas de estética, barbearias, spas, academias, estúdios e entre outros estabelecimentos de beleza ou bem-estar que tenham celebrado um contrato de parceria com a Lyndus (“Beauty Spots” ou “Parceiros”) e indivíduos que desejam adquirir os serviços de beleza oferecidos por tais Parceiros (“Usuários”), a fim de permitir que os Usuários comprem e façam uso dos serviços de beleza e bem-estar oferecidos pelo Parceiro por meio do aplicativo Lyndus.<br/><br/>
              Havendo dúvidas, comentários ou preocupações sobre estes Termos de Uso ou sobre os Serviços, entre em contato conosco: ajuda@lyndus.com.br, Rua Padre Anchieta, nº 2348, sala 1903, bairro Bigorrilho, CEP 80.730-001, Curitiba-PR. <br/><br/>
              <li>Termos e Condições de uso da Lyndus</li><br/>
              Estes Termos e Condições de Uso (os "Termos") são um contrato vinculativo entre você e a LYNDUS S/A, CNPJ nº 43.616.904/0001-59, sediada na Rua Padre Anchieta, nº 2348, Sala 1903, bairro Bigorrilho, CEP 80-730-001, Curitiba-PR, Brasil ("Lyndus", "Nós", "nos" e equivalentes).<br/><br/>
              Você deve concordar e aceitar todos os Termos ou não terá o direito de utilizar os serviços. <b>A sua utilização dos serviços, em qualquer forma, indica que você concorda com todos esses Termos, e estes permanecerão em vigor enquanto você utilizar os Serviços.<br/><br/>
              AVISO: Leia estes termos com atenção. Eles tratam de informações importantes sobre os serviços prestados, incluindo quaisquer encargos ou montantes que poderemos cobrar de você. Estes Termos incluem informações sobre alterações futuras destes Termos, renovações automáticas, limitações de responsabilidade, renúncia de ação coletiva e resolução de litígios por arbitragem em oposição à resolução via tribunais.</b><br/><br/>
              Buscamos constantemente inovar e melhorar os nossos serviços e, assim, poderá haver necessidade de alterar estes Termos juntamente com os serviços. Reservamo-nos o direito de alterar os Termos a qualquer momento, mas se os alterarmos, levaremos isso a sua atenção ao colocar um aviso no site da Lyndus (https://www.lyndus.com.br), ao enviar-lhe um e-mail e/ou por outros meios.<br/><br/>
              <b>Se não concordar com os novos Termos, você poderá rejeitá-los e você não deve começar ou continuar a utilizar o aplicativo, o site ou os serviços Lyndus. Se utilizar os serviços de qualquer forma, depois que uma alteração nos termos estiver em vigor, tal ação indicará que você concorda com todas as alterações.</b><br/><br/>
              Com exceção às alterações realizadas pela Lyndus, conforme descrito neste instrumento, nenhuma outra alteração ou modificação destes Termos será eficaz, a menos que seja por escrito e assinada por você e por nós.<br/><br/>
              <li>Privacidade</li><br/>
              A Lyndus leva a privacidade de todos os seus usuários muito a sério. Não coletamos ou solicitamos intencionalmente dados de identificação pessoal de menores de 16 anos; se você possuir menos de 16 anos, não tente se registrar nos serviços nem nos envie quaisquer dados pessoais. <br/><br/>
              Se tomarmos conhecimento de que coletamos Dados Pessoais de uma pessoa com menos de 16 anos, eliminaremos esses dados o mais rapidamente possível. Se acreditar que uma pessoa menor de 16 anos pode ter nos fornecido seus Dados Pessoais, entre em contato conosco em ajuda@lyndus.com.br.<br/><br/>
              Ao utilizar os serviços, você está nos autorizando a coletar, armazenar, manter e usar todos e quaisquer dados fornecidos no cadastro, bem como os dados gerados durante a utilização do aplicativo.<br/><br/>
              <li>Sua conta na Lyndus</li><br/>
              Os usuários que desejarem acessar o aplicativo deverão criar uma conta. A fim de criar uma conta, o usuário deve fornecer dados básicos de registo (iniciando pelo CPF) e seguir os passos indicados nas telas até a conclusão básica do cadastro.<br/><br/>
              Reforçamos que para utilizar os serviços por completo e possibilitar o correto funcionamento de algumas funcionalidades, tais como agendamento, pagamento, aquisição de créditos e usufruir de promoções, bônus e demais campanhas, você deverá complementar o cadastro, visto que algumas informações de contato são necessárias e exigidas para tal. Assim, você está nos autorizando a coletar, armazenar, manter e usar todos e quaisquer dados fornecidos no cadastro, bem como os dados gerados durante a utilização do aplicativo.<br/><br/>
              Ressaltamos, ainda, que não fazemos uso de dados pessoais sensíveis, assim entendidos como aqueles relativos à origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico.<br/><br/>
              É permitido que você mantenha apenas uma única conta no aplicativo. Você se compromete a nos fornecer os dados de registro exatos e completos, bem como a atualizar todos os dados de registo sempre que houver uma alteração em qualquer desses dados. Assim, a Lyndus se reserva o direito de validar seus dados de registro a qualquer momento, e pode solicitar quaisquer dados e documentos adicionais que a Lyndus considerar pertinentes, a fim de verificar seus dados de registro.<br/><br/>
              No caso em que se constatar que quaisquer dados de registro sejam inverídicos ou incorretos, a Lyndus se reserva o direito de suspender ou encerrar a conta do Usuário (sem indenização ou reembolso) ou tomar outras medidas que possam ser necessárias e adequadas. Você não pode selecionar como sua Identificação de usuário Lyndus um nome sobre o qual não possua o direito de uso, ou o nome de outra pessoa com a intenção de representá-la. Você não pode transferir, vender ou arrendar a sua conta a ninguém sem a nossa autorização prévia por escrito.<br/><br/>
              Você declara e garante que possui mais de 18 anos para celebrar um contrato vinculativo (ou se não for, que possui mais de 16 anos e já recebeu a permissão dos seus pais ou do responsável legal para utilizar os serviços e que seus pais ou responsável legal concordaram com estes Termos em seu nome).<br/><br/>
              Do mesmo modo, você declara que é civilmente capaz ou que, se for o caso, recebeu autorização de seu responsável legal para tanto.<br/><br/>
              Se estiver concordando com estes Termos em nome de uma organização ou entidade, você declara e garante que está autorizado a concordar com estes Termos em nome da organização ou entidade, bem como está autorizado a vinculá-la a estes Termos (nesse caso, as referências a "você" e equivalentes nestes Termos constituem uma exceção nesta frase e se referem a essa organização ou entidade).<br/><br/>
              Você somente utilizará os Serviços para o seu uso pessoal, próprio e interno – não em nome ou em benefício de terceiros – e apenas de uma forma que cumpra todas as leis que lhe sejam aplicáveis. Se a sua utilização dos Serviços for proibida pela legislação aplicável, você não está autorizado a utilizar os serviços. Não podemos e não seremos responsáveis por sua utilização dos serviços de uma forma que infrinja a lei.<br/><br/>
              Você não compartilhará a sua conta ou senha com ninguém e deverá proteger a segurança de sua conta e senha. Você é responsável por qualquer atividade associada à sua conta. Você concorda em notificar imediatamente a Lyndus no caso de qualquer uso não autorizado da sua conta.<br/><br/>
              <li>Seus compromissos com a Lyndus</li><br/>
              A utilização dos nossos serviços está sujeita às seguintes restrições adicionais:<br/><br/>
              Você declara, garante e concorda que não contribuirá com qualquer Conteúdo ou Envio de Usuário (cada um desses termos é definido no preâmbulo destes termos) ou de outra forma utilizará os serviços ou interagirá com os serviços de uma forma que:<br/><br/>
              <ul>
                <li>Infrinja ou viole os direitos de propriedade intelectual ou outros direitos de qualquer outra pessoa ou entidade (incluindo a Lyndus);</li>
                <li>Viole qualquer lei ou regulamento, incluindo, sem limitação, quaisquer leis de controle de exportação aplicáveis;</li>
                <li>Seja prejudicial, fraudulenta, enganosa, ameaçadora, assediadora, difamatória, obscena ou de outra forma censurável;</li>
                <li>Coloque em risco a segurança da sua conta Lyndus ou de qualquer outro (por exemplo, permitindo que outra pessoa acesse os serviços como se fosse você);</li>
                <li>Tente, de qualquer forma, obter a senha, conta ou outros dados de segurança de qualquer outro usuário;</li>
                <li>Viole a segurança de qualquer rede de computador, ou quebre quaisquer senhas ou códigos de criptografia de segurança;</li>
                <li>Execute lista de mailing, Listserv, qualquer forma de resposta automática ou "spam" sobre os Serviços, ou quaisquer processos que executam ou são ativados enquanto você não estiver logado nos Serviços, ou que interfiram com o bom funcionamento dos Serviços;</li>
                <li>Utilize rastreadores de rede, extratores de conteúdo ou spiders em qualquer página, dados, ou parte dos Serviços e Conteúdo ou relacionados com estes (através da utilização de meios manuais ou automatizados);</li>
                <li>Copie ou armazene qualquer parcela significativa do Conteúdo;</li>
                <li>Decompile, faça engenharia reversa, ou de outra forma tente obter o código-fonte ou ideias ou dados subjacentes dos Serviços ou relacionados a estes.</li>
              </ul>
              Uma violação de qualquer dos itens anteriores é motivo para o cancelamento da sua conta e do seu direito de usar ou acessar os Serviços, sem direito a qualquer tipo de reembolso, indenização ou compensação.<br/><br/>
              Além disso, o nome "Lyndus", o site e os softwares, bancos de dados, redes e arquivos que permitem que você acesse os serviços são de propriedade da Lyndus ou parceiros, protegidos pelas leis e regulamentos que regem as marcas registradas, patentes e projetos industriais. É proibido o uso indevido ou reprodução, total ou parcial, do nosso nome ou de outra propriedade intelectual relativas aos serviços sem a permissão expressa da Lyndus.<br/><br/>
              Os materiais expostos ou executados ou disponíveis por meio dos Serviços, incluindo, entre outros, texto, gráficos, dados, artigos, fotos, imagens, ilustrações, Envios do Usuário e assim por diante (tudo o que precede, o "Conteúdo") são protegidos por direitos autorais e/ou outras leis de propriedade intelectual. <br/><br/>
              Você se compromete a respeitar todos os avisos de direitos autorais, normas de marca registrada, dados e restrições contidos em qualquer conteúdo que acessar por meio dos Serviços, e você não poderá usar, copiar, reproduzir, modificar, traduzir, publicar, transmitir, distribuir, executar, carregar, exibir, licenciar, vender, comercializar ou de outra forma explorar, para qualquer finalidade, qualquer conteúdo que não lhe pertence, (i) sem o consentimento prévio do proprietário desse Conteúdo ou (ii) de uma forma que viole os direitos de outra pessoa (incluindo a 'Lyndus').<li>Condições Gerais</li><br/>
              Você entende e declara que a Lyndus é a proprietária dos Serviços. Você não modificará, publicará, transmitirá, participará da transferência ou venderá, reproduzirá (exceto conforme expressamente fornecido nesta seção), criará trabalhos derivados, ou de outra forma explorará qualquer um dos Serviços.<br/><br/>
              Qualquer coisa que você postar, carregar, compartilhar, armazenar ou de outra forma disponibilizar por meio dos serviços (incluindo, sem limitação, imagens, avaliações, comentários e outros conteúdos que serão exibidos no aplicativo Lyndus) constitui o seu "Envio de Usuário". Alguns Envios do Usuário podem ser visualizados por outros usuários. <br/><br/>
              Para exibir seus Envios do Usuário no aplicativo Lyndus, ou em conexão com os Serviços, e a fim de permitir que outros usuários possam apreciá-los (quando aplicável), você nos concede determinados direitos sobre tais Envios do Usuário. <br/><br/>
              Observe que todas as licenças a seguir estão sujeitas à nossa Política de Privacidade, na medida em que se referem aos Envios do Usuário que também são seus dados de identificação pessoal. Para todos os Envios do Usuário, você concede à Lyndus uma licença para traduzir, modificar (para fins técnicos, por exemplo, com o objetivo de garantir que o seu conteúdo fique visível em um iPhone, bem como um computador) e reproduzir e de outra forma agir com relação a tais Envios do Usuário, em cada caso para nos permitir operar os Serviços, conforme descrito em mais detalhes abaixo. Trata-se apenas de uma licença – a sua propriedade sobre os Envios do Usuário não é afetada.<br/><br/>
              Ao armazenar um Envio do Usuário em sua própria conta pessoal no aplicativo Lyndus, de forma que este não fique visível a qualquer outro usuário, exceto você (um "Envio Pessoal do Usuário"), você concede à Lyndus a licença acima, bem como uma licença para exibir, executar e distribuir o seu Envio Pessoal do Usuário com o único propósito de tornar esse Envio Pessoal do Usuário acessível a você, bem como para fornecer os Serviços necessários para isso.<br/><br/>
              Ao compartilhar um Envio do Usuário de uma forma que somente determinados usuários especificados possam visualizá-lo (por exemplo, publicações do Facebook para um ou mais usuários) (um "Envio de Usuário de Público Limitado"), você concede à Lyndus as licenças acima, bem como uma licença para exibir, executar e distribuir seu Envio de Usuário de Público Limitado com o único propósito de tornar tal Envio de Usuário de Público Limitado acessível a quaisquer outros usuários especificados, bem como para fornecer os serviços necessários para isso. <br/><br/>
              Além disso, você concede a esses outros usuários especificados uma licença para acessar esse Envio de Usuário de Público Limitado, e usá-lo e exercer todos os direitos sobre ele, conforme permitido pela funcionalidade dos Serviços.<br/><br/>
              Ao compartilhar um Envio de Usuário publicamente nos Serviços e/ou de uma forma que mais usuários além de você ou determinados usuários especificados possam visualizá-lo, ou se você nos fornecer (em um e-mail direto ou de outra forma) qualquer feedback, sugestões, melhorias, aperfeiçoamentos e/ou solicitações de recursos relacionados com os Serviços (cada um dos anteriores, um “Envio Público do Usuário”), você concede à Lyndus as licenças acima, bem como uma licença para exibir, executar e distribuir o seu Envio Público do Usuário com a finalidade de tornar esse Envio Público do Usuário acessível a todos os usuários da Lyndus, para fornecer os serviços necessários para isso, bem como todos os outros direitos necessários para usar e exercer todos os direitos sobre esse Envio Público do Usuário em relação aos Serviços para qualquer finalidade, desde que a Lyndus tente notificá-lo caso ela venha a usar seu Envio Público do Usuário por qualquer razão que não seja a de exibi-lo nos serviços. Além disso, você concede a todos os outros usuários do Serviço uma licença para acessar esse Envio Público do Usuário, e para usá-lo e exercer todos os direitos sobre ele, conforme permitido pela funcionalidade dos Serviços.<br/><br/>
              Você concorda que as licenças que conceder são isentas de direitos autorais, perpétuas, sublicenciáveis, irrevogáveis e em todo o mundo, contanto que, ao cancelar a sua conta Lyndus, pararemos de usar seus Envios do Usuário (que não sejam Envios Públicos do Usuário que podem permanecer totalmente disponíveis) a outros usuários (se aplicável), mas você entende e concorda que mesmo se a Lyndus excluir todos os seus dados pessoais, seus Envios do Usuário podem permanecer visíveis em outros lugares, à medida que eles podem ter sido copiados ou armazenados por outros usuários.<br/><br/>
              A Lyndus possui e pode usar quaisquer dados agregados e anônimos derivados ou incorporados a partir dos dados recebidos por meio da sua conta, mas não de uma forma que possa identificá-lo pessoalmente.<br/><br/>
              Finalmente, você entende e concorda que a Lyndus, ao executar as etapas técnicas necessárias para fornecer os serviços aos usuários (incluindo você), poderá precisar fazer alterações em seus Envios do Usuário a fim de deixá-los em conformidade e os adaptar aos requisitos técnicos relativos a redes, dispositivos, serviços ou mídia de conexão, e as licenças anteriores incluem os direitos de realizar tais ações.<br/><br/>
              Ao perceber que algo nos Serviços viola os direitos autorais saiba que cumprimos rigorosamente a lei norte-americana dos Direitos Autorais do Milênio Digital (Digital Millennium Copyright Act, "DMCA"), que se refere aos prestadores de serviços online, como a Lyndus, solicitados a remover o material que supostamente viole os direitos autorais de alguém. Respeitamos os direitos de propriedade intelectual dos outros, e reservamo-nos o direito de excluir ou desativar o Conteúdo alegado de estar em violação, bem como encerrar as contas de infratores alegados reincidentes.<br/><br/>
              Quaisquer dados ou conteúdo publicamente postados ou transmitidos privativamente através dos serviços são de exclusiva responsabilidade da pessoa que originou tal conteúdo, e o seu acesso a todos esses dados e conteúdo é em seu próprio risco, e não somos responsáveis por quaisquer erros ou omissões nesses dados ou conteúdo ou por quaisquer danos ou perdas que se possa sofrer em conexão com eles. Não podemos controlar e não temos nenhum dever de tomar qualquer iniciativa sobre como se pode interpretar e usar o Conteúdo ou quais ações você pode tomar como resultado de ter sido exposto ao Conteúdo, e você nos liberta, por meio deste documento, de toda a responsabilidade por você ter adquirido ou não adquirido Conteúdo através dos Serviços.<br/><br/>
              Não podemos garantir a identidade de qualquer usuário com quem você interage ao utilizar os Serviços e não somos responsáveis por quais usuários obtêm acesso aos Serviços.<br/><br/>
              Você é responsável por todo Conteúdo com o qual contribuir, de alguma forma, em relação aos Serviços, e você declara e garante que tem todos os direitos necessários para isso, na maneira em que você contribuir. Ao contribuir com qualquer conteúdo, você declara e garante que: (i) possui todas as licenças, autorizações necessárias, bem como os direitos de utilização de toda a propriedade intelectual para fazer tal contribuição, (ii) obteve todos os consentimentos necessários para fazer tal contribuição (se aplicável), (iii) registrou o conteúdo com as agências apropriadas (se aplicável), e (iv) incluirá todos os créditos necessários, visando a preservação dos direitos morais dos detentores dos direitos autorais (se aplicável). <br/><br/>
              Você manterá precisos e atuais todos os seus dados de registro. Você é responsável por toda a sua atividade em relação aos Serviços.<br/><br/>
              Os Serviços podem conter links ou conexões a sites ou serviços de terceiros que não são de propriedade ou controlados pela Lyndus. Ao acessar sites de terceiros ou utilizar serviços de terceiros, você aceita que existem riscos ao fazer isso, e que a Lyndus não é responsável por tais riscos. Incentivamos que esteja ciente, ao deixar os Serviços, de ler os termos e condições e a política de privacidade de cada site ou serviço de terceiros que você visitar ou utilizar.<br/><br/>
              A Lyndus não tem controle sobre, nem assume nenhuma responsabilidade em relação ao conteúdo, precisão, políticas de privacidade ou práticas ou opiniões expressas em quaisquer sites de terceiros, ou por qualquer terceiro com o qual você interagir por meio dos Serviços. Além disso, a Lyndus não vai e não pode monitorar, verificar, censurar ou editar o conteúdo de qualquer site ou serviço de terceiros. Ao utilizar os Serviços, você nos liberará e isentará de toda e qualquer responsabilidade decorrente do seu uso de qualquer site ou serviço de terceiros.<br/><br/>
              As suas interações com organizações e/ou indivíduos encontrados por meio dos Serviços, incluindo o pagamento e a entrega de mercadorias ou serviços e quaisquer outros termos, condições, garantias ou declarações associadas com tais transações são unicamente entre você e essas organizações e/ou indivíduos. Você deve fazer qualquer investigação que achar necessária ou adequada antes de prosseguir com qualquer transação com qualquer desses terceiros. Você concorda que a Lyndus não será responsabilizada por qualquer perda ou dano de qualquer tipo incorrido como resultado de quaisquer dessas negociações.<br/><br/>
              Se houver um litígio entre os participantes desta plataforma, ou entre os usuários e quaisquer terceiros, você concorda que a Lyndus não possui qualquer obrigação de se envolver em tal litígio. Na hipótese de você ter um litígio com um ou mais usuários e/ou parceiros, você liberará a Lyndus, seus diretores, dirigentes, funcionários, agentes e sucessores de quaisquer reivindicações, demandas e danos de qualquer tipo ou natureza, conhecidos ou desconhecidos, suspeitos ou não, divulgados ou confidenciais, decorrentes ou de qualquer forma relacionados a esses litígios e/ou nossos Serviços. <br/><br/>
              Estamos sempre buscando melhorar os Serviços, assim, estes podem mudar ao longo do tempo. Podemos suspender ou descontinuar qualquer parte dos Serviços, ou podemos introduzir novos recursos ou impor limites sobre determinados recursos ou restringir o acesso a partes ou a todos os Serviços. Avisaremos previamente quando fizermos uma alteração substancial nos Serviços. <br/><br/>
              Da mesma forma, reservamo-nos o direito de remover qualquer Conteúdo dos Serviços a qualquer momento e por qualquer motivo (incluindo, sem limitação, se alguém alegar que contribuiu com esse Conteúdo em violação destes Termos), a nosso exclusivo critério e sem aviso prévio.<br/><br/>
              Caso você queira deixar de utilizar a Lyndus, você é livre para fazer isso a qualquer momento, basta entrar em contato conosco pelo e-mail relacionamento@lyndus.com.br; consulte a nossa Política de Privacidade, bem como as licenças acima, para entender como nós trataremos os dados que nos fornecer depois de deixar de utilizar os nossos Serviços.<br/><br/>
              A Lyndus pode permitir que um Usuário cancele a Ativação de Créditos mediante notificação por escrito. Os usuários podem solicitar o cancelamento do serviço prestado pela Lyndus a qualquer momento após a ativação de valores, porém o valor ativado para a utilização no mês corrente, bem como eventuais bônus promocionais adicionais não serão passíveis de devolução; apenas não mais será processada a ativação de valores para os meses seguintes. Um usuário que solicitar o cancelamento do serviço e Ativações de Créditos pela Lyndus não estará sujeito a cobranças adicionais.<br/><br/>
              A Lyndus também é livre para encerrar (ou suspender o acesso a) o seu uso dos Serviços ou sua conta, por qualquer motivo, a nosso critério, incluindo sua violação destes Termos. A Lyndus possui o exclusivo direito para decidir se você está em violação de qualquer das restrições estabelecidas nestes Termos.<br/><br/>
              O encerramento da conta resultará na destruição de qualquer conteúdo associado à sua conta e, assim, tenha isso em mente antes de decidir encerrar a sua conta. Tentaremos enviar um aviso prévio antes da encerrarmos a sua conta, para que você possa recuperar quaisquer Envios do Usuários importantes que estiverem armazenados em sua conta (na medida permitida por lei e por estes Termos), mas não faremos isso se determinarmos que tal ação seja ilegal.<br/><br/>
              Se tiver cancelado a sua conta ou modificado os dados da conta por engano, entre em contato conosco imediatamente pelo e-mail relacionamento@lyndus.com.br – tentaremos ajudá-lo, porém, infelizmente, não podemos prometer que conseguiremos recuperar ou restaurar alguma coisa.<br/><br/>
              As disposições que, pela sua natureza, devem prevalecer à rescisão destes Termos deverão prevalecer após a rescisão. A título de exemplo, as seguintes disposições prevalecerão à rescisão: qualquer obrigação que você tenha que nos pagar ou indenizar, quaisquer limitações sobre a nossa responsabilidade, quaisquer termos em relação aos direitos de propriedade intelectual e termos sobre litígios entre nós, incluindo, sem limitação, o acordo de arbitragem. Você poderá escolher, dentre os serviços ofertados dentro da plataforma Lyndus, o que lhe melhor convier e de acordo com os recursos disponíveis.<br/><br/>
              Os créditos referentes aos benefícios recebidos, ou os créditos autonomamente carregados, ou os pagamentos recebidos pelos serviços não possuem prazo de validade para utilização enquanto sua conta estiver ativa. Nos casos de créditos recebidos como bônus promocionais, tais como: cupons de desconto, bônus por carregamento autônomo e créditos no formato de cashback, devido à natureza promocional relacionada a campanhas periódicas, terão tratamento diferenciado e expirarão dentro do prazo de 30 (trinta) dias contados da data do recebimento do referido bônus. <br/><br/>
              É importante que você esteja ciente de que a solicitação de encerramento da sua conta excluirá por completo todos os seus registros em nosso sistema, inclusive impossibilitando a recuperação do saldo que você possua. Para tanto, caso seja seu desejo a exclusão da sua conta, recomendamos que você consuma todo o seu saldo antes de solicitar o encerramento.<br/><br/>
              Nem a Lyndus nem seus licenciadores, fornecedores ou Parceiros fazem quaisquer declarações ou garantias relativas a qualquer conteúdo contido nos Serviços ou acessados por meio de sua plataforma, e não seremos responsabilizados pela exatidão, cumprimento de direitos autorais, legalidade, ou decência de qualquer material contido ou acessado através dos Serviços.<br/><br/>
              Não fazemos (e nem nossos licenciadores, fornecedores e Parceiros) nenhuma declaração ou garantia sobre sugestões ou recomendações de Produtos ou Serviços oferecidos ou adquiridos através da plataforma.<br/><br/>
              Os produtos e serviços adquiridos ou oferecidos (seguindo ou não tais recomendações e sugestões) através da plataforma são fornecidos "no estado em que se encontram" e sem qualquer garantia de qualquer tipo da Lyndus ou de outros (a menos que, no que diz respeito somente a esse outros, desde que inequívoca e expressamente por escrito por um terceiro designado em relação a um produto específico), incluindo sem limitação, garantias implícitas de comerciabilidade, adequação a uma finalidade específica, não violação ou de que o uso dos serviços ou sem erros. Alguns estados não permitem limitações na duração de uma garantia implícita, portanto, as limitações acima podem não se aplicar a você. Ou seja, a responsabilidade pela qualidade, resultado, apresentação, atendimento, ambiente e execução dos serviços é integral e exclusiva de seus prestadores e respectivos estabelecimentos parceiros (Beauty Spots), não sendo a Lyndus, em nenhum nível, garantidora, responsável ou corresponsável por quaisquer dessas questões.<br/><br/>
              Aplicamos, na máxima extensão permitida pela legislação aplicável, a limitação de responsabilidade. Ou seja, em nenhuma circunstância e sob nenhuma teoria jurídica (incluindo, sem limitação, ato ilícito, contrato, responsabilidade estrita, ou outros) a Lyndus (ou seus licenciantes, fornecedores ou parceiros) serão responsáveis perante a você ou a qualquer outra pessoa em função de: (a) qualquer dano indireto, especial, incidental ou consequente de qualquer tipo, incluindo danos por lucros cessantes, perda da boa-fé, paralisações trabalhistas, decretos legais que estabeleçam restrições ou lockdown, precisão de resultados ou falha ou mau funcionamento de computador ou (b) qualquer montante, no agregado, acima de (i) US$ 100 ou (ii) os montantes pagos pelo usuário à Lyndus em relação aos serviços no prazo de 12 (doze) meses anteriores a tal reclamação aplicável, ou (c) qualquer questão fora do nosso controle razoável.<br/><br/>
              Você concorda em indenizar e isentar a Lyndus, suas afiliadas, dirigentes, agentes, funcionários e parceiros de e contra todas e quaisquer reivindicações, responsabilidades, danos (reais e consequentes), perdas e despesas (incluindo honorários advocatícios) decorrentes de qualquer forma, relativa a quaisquer reclamações de terceiros relacionadas com (a) seu uso dos Serviços (incluindo quaisquer ações ajuizadas por terceiros utilizando sua conta) e (b) sua violação destes Termos.<br/><br/>
              Você não pode ceder, delegar ou transferir estes Termos ou seus direitos ou obrigações no âmbito do presente documento, ou a sua conta de Serviços, de qualquer maneira (por força da lei ou de outra forma) sem o consentimento prévio por escrito da Lyndus. Podemos, entretanto, transferir, ceder ou delegar estes Termos e os nossos direitos e obrigações sem qualquer consentimento.<br/><br/>
              Todos os itens destes Termos e Condições de Uso são regidos pelas leis do Brasil. Para todas as disputas legais ou assuntos, a menos que exigido por lei, será eleito o foro central da Comarca da Região Metropolitana de Curitiba. Isso não se aplica a transações legais com consumidores, que são regidas pelo Código de Defesa do Consumidor e demais legislações aplicáveis.<br/><br/>
              Você será responsável por pagar, reter, arquivar e relatar todos os eventuais impostos, direitos e outras aferições governamentais associadas com a sua atividade relacionada aos Serviços. A sua ou nossa falha em exercitar, de alguma forma, qualquer direito aqui expresso não se considerará uma renúncia a quaisquer direitos adicionais do presente instrumento.<br/><br/>
              Se qualquer disposição destes Termos for considerada inválida ou inexequível, essa disposição será limitada ou eliminada, na medida mínima necessária, para que estes Termos permaneçam executórios e em pleno vigor e efeito. Você e a Lyndus concordam que estes Termos são a declaração completa e exclusiva do entendimento mútuo entre você e a Lyndus, e que estes Termos substituem e cancelam todos os acordos anteriores, orais ou por escrito, comunicações e outros entendimentos relacionados com o objeto destes Termos. Por meio deste instrumento, você reconhece e concorda que você não é um funcionário, agente, ou empreendimento conjunto da Lyndus, e você não tem qualquer vínculo pessoal com a empresa Lyndus ou autoridade de qualquer natureza para vincular a Lyndus em qualquer aspecto de qualquer natureza.<br/><br/>
              <h2>Política de Privacidade</h2>
              <br/>
              Na Lyndus levamos a sua privacidade muito a sério. Leia nossa Política de Privacidade a seguir para conhecê-la melhor.<br/><br/>
              Ao aceitar os nossos Termos e Condições de Uso e a nossa Política de Privacidade para utilizar os Serviços, você reconhece que aceita as práticas e políticas descritas neste documento, bem como consente que coletemos, usemos, tratemos e compartilhemos os seus dados das maneiras descritas a seguir.<br/><br/>
              Lembre-se que a sua utilização dos Serviços Lyndus será, em todos os momentos, sem prejuízo ao disposto nos Termos e Condições de Uso, que incorpora a presente Política de Privacidade. Quaisquer termos que utilizamos nesta Política sem sua respectiva definição possuem as definições que lhes foram atribuídos nos Termos e Condições de Uso.<br/><br/>
              A Lyndus é uma plataforma que atua como conectora entre salões de beleza, clínicas de estética, barbearias, spas, academias, estúdios e outros estabelecimentos de beleza ou bem-estar que tenham celebrado um contrato de parceria com a Lyndus (“Beauty Spots” ou “Parceiros”) e indivíduos que desejam adquirir os serviços de beleza oferecidos por tais Parceiros (“Usuários” ou ‘’Você”), a fim de permitir que você os compre e faça uso dos serviços de beleza e bem-estar oferecidos (‘’Serviços’’) pelo Parceiro por meio do aplicativo Lyndus.<br/><br/>
              A Lyndus pertence e é operada pela LYNDUS S/A, CNPJ nº 43.616.904/0001-59, sediada na Rua Padre Anchieta, nº 2348, Sala 1903, bairro Bigorrilho, CEP 80-730-001, Curitiba-PR, Brasil ("Lyndus", "Nós", "nos" e equivalentes). Esta Política de Privacidade abrange o tratamento de dados pessoais ("Dados Pessoais") que coletamos quando você estiver acessando ou utilizando nossos Serviços (seja individualmente ou por meio do seu empregador), e se aplica onde atuamos como um controlador de dados – nos casos em que determinamos como e por que os seus Dados Pessoais estão sendo tratados. A presente Política não se aplica a práticas das empresas que não possuímos ou controlamos ou às pessoas que não gerenciamos, na medida em que não compartilhamos seus Dados Pessoais com tais empresas ou pessoas.<br/><br/>
              Se tiver quaisquer perguntas, comentários ou preocupações sobre esta Política de Privacidade, entre em contato conosco: ajuda@lyndus.com.br.<br/><br/>
              Coletamos vários tipos de Dados Pessoais de nossos usuários, conforme explicado em mais detalhes abaixo, e usamos esses Dados Pessoais internamente em conexão com os nossos serviços, incluindo personalizar, fornecer e melhorar os nossos serviços, para que você possa configurar um perfil e conta de usuário, para que possamos entrar em contato com você e a fim de permitir que outros usuários entrem em contato com você, bem como visando atender suas solicitações relativas a determinados produtos e serviços e analisar como você usa os Serviços.<br/><br/>
              Em determinadas circunstâncias, também podemos compartilhar alguns Dados Pessoais com terceiros, mas somente como descrito abaixo.<br/><br/>
              Conforme observado nos Termos de uso, não coletamos ou solicitamos intencionalmente Dados Pessoais de pessoas menores de 16 anos. Se tiver menos de 16 anos, não se registre nos Serviços nem envie quaisquer Dados Pessoais para nós. Se tomarmos conhecimento de que coletamos Dados Pessoais de uma pessoa com menos de 16 anos, eliminaremos esses dados o mais rápido quanto possível. Se acreditar que uma pessoa menor de 16 anos pode ter nos fornecido seus Dados Pessoais, entre em contato conosco em ajuda@lyndus.com.br.<br/><br/>
              Estamos constantemente buscando melhorar os nossos Serviços, assim podemos precisar alterar esta Política de Privacidade eventualmente, entretanto, vamos alertá-lo sobre essas mudanças, colocando um aviso no site da Lyndus (https://www.lyndus.com.br), enviando-lhe um e-mail e/ou por outros meios. Observe que se tiver optado por não receber nossos e-mails de aviso legal (ou se ainda não nos forneceu seu endereço de e-mail), os avisos legais ainda regerão o seu uso dos Serviços, e você ainda será responsável por os ler e entender. Se decidir usar os Serviços após a publicação de quaisquer alterações da Política de Privacidade, você deverá aceitar as alterações consoante suas condições.<br/><br/>
              A Lyndus possui um produto corporativo chamado LyndusFazBem, pelo qual as empresas poderão conceder créditos para seus colaboradores utilizarem dentro da plataforma Lyndus e consumir em serviços prestados pelos Beauty Spots cadastrados. Nesse caso, a Lyndus coleta os dados que a empresa fornecedora do benefício para seus colaboradores nos ceder, visto que a fim de prestar os nossos Serviços, podemos receber e armazenar Dados Pessoais sobre você, os quais podem ser compartilhados conosco por seu empregador. Esses dados envolvem o seu nome completo, seu CPF, eventualmente o endereço de e-mail corporativo e, em alguns casos, o número de identificação do funcionário.<br/><br/>
              Podemos usar esses dados para contactá-lo, fazer referências cruzadas com outros Dados Pessoais que podemos manter sobre você em conformidade com esta Política, bem como compartilhar esses dados com o Beauty Spot que você escolher e com nossos parceiros comerciais, conforme previsto na presente Política.<br/><br/>
              Por meio deste, você reconhece que podemos receber Dados Pessoais sobre você do seu empregador e concorda com o nosso tratamento e compartilhamento desses dados nos termos desta Política. A base jurídica deste processamento é o consentimento que você concede por meio desta Política.<br/><br/>
              A Lyndus também coleta, recebe e armazena quaisquer dados que você nos forneça conscientemente. Especificamente, por meio do processo de registro de conta e/ou por meio das suas configurações de conta, coletamos seu nome completo, endereço de e-mail, número de telefone, dados de cartão de crédito/débito, dados da conta de débito, credenciais de conta de terceiros (por exemplo, suas credenciais de acesso ao Facebook/Instagram/WhatsApp), data de nascimento, endereço, gênero, sites pessoais e categorias favoritas. Ao fornecer acesso aos Serviços por meio de um site ou serviços de terceiros (como o Facebook/Instagram/WhatsApp), você entende que determinados conteúdos e/ou dados destas contas ("Dados da Conta de Terceiros") podem ser transmitidos para a sua conta conosco e que os Dados da Conta de Terceiros transmitidos aos nossos Serviços são cobertos pela presente Política de Privacidade. Determinados dados podem ser necessários para se registrar conosco ou para aproveitar alguns de nossos recursos.<br/><br/>
              Podemos nos comunicar com você se tiver nos fornecido os meios para isso. Por exemplo, se você tiver nos fornecido o seu endereço de e-mail, podemos enviar ofertas por e-mails promocionais em nome de outras empresas ou um e-mail sobre o seu uso dos Serviços. Ao nos fornecer o seu número de telefone celular, endereço de e-mail ou credenciais de conta do Facebook, você confirma que quer que a Lyndus lhe envie os dados que achar que podem ser de seu interesse, incluindo, sem limitação, promoções e atualizações sobre os Parceiros Lyndus, e você concorda em receber e-mails, SMS, notificações push e mensagens nas redes sociais. Se não quiser receber nossas comunicações, indique suas preferências e, para isso, clique no link de descadastramento que aparecerá em todos os e-mails ou entre em contato pelo e-mail relacionamento@lyndus.com.br. A Lyndus usará todos os esforços razoáveis para realizar o seu descadastramento dentro de 72 horas a partir da data de recepção da solicitação.<br/><br/>
              Podemos usar esses dados para contactá-lo, fazer referências cruzadas com outros Dados Pessoais que podemos manter sobre você em conformidade com esta Política, bem como compartilhar esses dados com o ESTABELECIMENTO que você escolher e com nossos parceiros comerciais, conforme previsto na presente Política.<br/><br/>
              Também podemos compartilhar seus dados com parceiros de agendamento com os quais você escolheu agendar categorias, mas isso somente acontecerá se você concordar, em cada momento, ao agendar uma categoria.<br/><br/>
              Além desses, alguns dados são coletados automaticamente sempre que você interagir com os nossos Serviços, por meio do nosso site ou via um aplicativo móvel. Automaticamente receberemos e registraremos dados em nosso servidor a partir do seu navegador ou dispositivo, os quais podem incluir seu endereço IP, dados de geolocalização, identificação do dispositivo, dados de "cookie" (veja abaixo), o tipo de navegador e/ou dispositivo utilizado para acessar nossos Serviços, a página ou recurso solicitado e o tempo de acesso.<br/><br/>
              Podemos utilizar estes dados para lhe fornecer uma experiência personalizada, com base em seus padrões de uso, ou para o remarketing, impressão de relatórios, gerenciamento ou outras análises. Também podemos usá-los para melhorar os Serviços – por exemplo, esses dados podem nos dizer com qual frequência os usuários usam um recurso específico dos Serviços e, dessa forma, podemos usar esse conhecimento para melhorar a experiência do usuário.<br/><br/>
              "Cookies" são identificadores que transferimos ao seu navegador ou dispositivo que nos permitem reconhecê-lo, bem como nos informa como e quando as páginas e recursos são visitados em nossos Serviços e por quantas pessoas.<br/><br/>
              Por meio de cookies, podemos coletar dados sobre sua atividade on-line depois que sair dos nossos Serviços. Assim como outros dados de uso que coletamos, esses dados nos permitem melhorar os serviços e personalizar a sua experiência on-line e como de outra forma descrita nesta Política de Privacidade. Atualmente, nossos Serviços não são compatíveis com solicitações de "não rastreamento", o que significa que poderemos coletar dados sobre sua atividade on-line enquanto estiver usando os Serviços.<br/><br/>
              Especificamente, usamos os cookies de acordo com as seguintes finalidades:<br/><br/>
              <ul>
                <li>Autenticação e o status de logon – usamos os cookies para identificá-lo ao abrir o nosso site e para saber se você está conectado ou não ao nosso site;</li>
                <li>Publicidade – usamos os cookies para nos ajudar a identificar seus padrões de uso em nosso site e aplicativo, bem como para nos auxiliar a exibir anúncios que sejam relevantes a você;</li>
              </ul>
              Usamos o Google Analytics para analisar o uso do nosso site e do nosso aplicativo. O Google coleta dados sobre a utilização do site e de aplicativo através de cookies e usa esses dados para criar relatórios sobre a utilização do nosso site e aplicativo.<br/><br/>
              A política de privacidade do Google está disponível em: www.google.com/policies/privacy/, e ao usar o link www.google.com/settings/ads, o usuário pode configurar ou desvincular alguns desses métodos de coleta de dados.<br/><br/>
              Além disso, é possível alterar suas preferências no navegador ou dispositivo, a fim de impedir ou limitar a aceitação de cookies no dispositivo, entretanto, essa ação pode impedi-lo de desfrutar de alguns dos nossos recursos. Novamente, esta Política de Privacidade não abrange a utilização de cookies por quaisquer terceiros, e não somos responsáveis por suas práticas e políticas de privacidade. Esteja ciente de que os cookies colocados por terceiros podem continuar a rastrear suas atividades on-line, mesmo após ter deixado nossos Serviços, e esses terceiros podem não cumprir a solicitação de "não rastreamento" que você pode ter definido usando o navegador ou dispositivo.<br/><br/>
              Não arrendamos, vendemos ou transferimos o seu formulário de Dados Pessoais a ninguém, exceto conforme expressamente previsto abaixo. Podemos compartilhar seus Dados Pessoais com terceiros, conforme descrito a seguir:<br/><br/>
              <li>Beauty Spots: Podemos compartilhar alguns dos seus Dados Pessoais com esses para que elas possam inscrevê-lo em seus sistemas e a fim de permitir que você participe dos serviços. Os únicos dados que compartilhamos com os Beauty Spots são o seu nome completo, número de telefone, endereço de e-mail e informações de passe diário (check-in) geradas pelo nosso sistema.</li><br/>
              Podemos remover a identificação pessoal dos seus Dados Pessoais para que você não seja identificado como uma pessoa e fornecer os dados aos Beauty Spots ou a um cliente corporativo (ou seja, o seu empregador). Além disso, podemos fornecer dados de uso agregado aos Salões/Barbearias ou clientes corporativos (ou permitir que parceiros ou clientes corporativos coletem esses dados de você), os quais podem usar esses dados para entender quantas vezes e de que maneira os usuários usam nossos Serviços, de forma que eles também possam proporcionar aos usuários uma experiência ideal.<br/><br/>
              No entanto, nunca divulgaremos o uso agregado ou dados com a identificação removida a um Beauty Spot ou cliente corporativo de forma que isso possa identificá-lo como um indivíduo, direta ou indiretamente. A Lyndus armazena dados que são usados na forma de estatísticas agregadas e genéricas ou relatórios, a fim de obter uma melhor compreensão dos perfis de usuário com o objetivo de melhorar os produtos e serviços oferecidos pela Lyndus.<br/><br/>
              Podemos, eventualmente, permitir que anunciantes e/ou parceiros comerciais ("Anunciantes") escolham os dados demográficos dos usuários que verão seus anúncios e/ou ofertas promocionais, e você concorda que podemos fornecer quaisquer dados coletados de forma não pessoalmente identificável a um Anunciante, para que este selecione o público adequado para os anúncios e/ou ofertas. Por exemplo, podemos usar o fato de que você estar localizado em Curitiba para mostrar anúncios ou ofertas das empresas de Curitiba, mas não diremos a tais empresas quem é você. Ou podemos permitir que os Anunciantes exibam seus anúncios aos usuários com padrões de uso semelhante ao seu, mas não divulgaremos dados de uso aos Anunciantes, exceto na forma agregada, bem como não os divulgaremos de uma forma que possa identificá-lo pessoalmente.<br/><br/>
              Vale observar que se um Anunciante nos solicitar para mostrar um anúncio a um determinado público ou segmento de público, e você responder a esse anúncio, o Anunciante pode concluir que você se encaixa na descrição do público-alvo que ele almejava alcançar<br/><br/>
              Usamos ferramentas como Google Tag Manager, Facebook, Instagram, WhatsApp e LinkedIn para nos comunicar com os usuários, com base nos dados coletados por esses anunciantes e também para nos comunicar com os usuários com base nos dados que coletamos em nosso site e ou via um aplicativo móvel.<br/><br/>
              <li>Empresas Afiliadas: Em determinadas situações, as empresas ou sites de terceiros que são filiados, eventualmente, vendem ou fornecem produtos ou serviços a você por meio de ou em conexão com os Serviços (individualmente ou em conjunto conosco). É possível reconhecer quando uma empresa afiliada está associada a um serviço ou transação, e vamos compartilhar os seus Dados Pessoais com essa empresa afiliada apenas na medida em que estes estiverem relacionados com tal transação ou serviço. Não temos controle sobre as políticas e práticas de empresas ou sites de terceiros quanto à privacidade, ou qualquer outro fator. Assim, se optar por tomar parte em qualquer transação ou serviço relacionado com uma empresa ou site afiliado, reveja todas as políticas dessas empresas ou sites.</li><br/>
              <li>Nossos Agentes: Utilizamos outras empresas e pessoas para executar tarefas em nosso nome e precisamos compartilhar seus dados com eles para lhe fornecer produtos ou serviços; por exemplo, além da plataforma própria, também utilizamos uma empresa de processamento de pagamentos que é responsável por receber e processar suas transações de cartão de crédito em nosso nome. A menos que tenhamos comunicado de outra forma, nossos agentes não têm qualquer direito de utilizar os Dados Pessoais compartilhados com eles além do que for necessário para nos ajudar.</li><br/>
              <li>Inscrições e perfis de usuário: Determinados dados de conta, incluindo seu nome, localização e qualquer conteúdo de vídeo ou imagem que um usuário carregar nos Serviços, podem ser exibidos a outros usuários para facilitar a interação do usuário dentro dos Serviços ou atender uma solicitação relativa aos nossos Serviços. Lembre-se que qualquer conteúdo que enviar ao seu perfil de usuário público, juntamente com quaisquer dados pessoais ou conteúdo que voluntariamente divulgar on-line de alguma maneira, que outros usuários poderão visualizar (em fóruns de discussão, mensagens, áreas de bate-papo etc.), tornam-se publicamente disponíveis, podendo ser coletados e utilizados por qualquer pessoa.</li><br/>
              O seu nome de usuário também pode ser exibido a outros usuários, se e quando você enviar mensagens ou comentários, bem como ao carregar imagens ou vídeos através dos Serviços, e outros usuários podem entrar em contato com você por meio de mensagens e comentários. Além disso, ao se inscrever nos Serviços através de um serviço ou site de rede social de terceiros, a sua lista de "amigos" desse site ou serviço pode ser automaticamente importada aos Serviços, e tais "amigos", se eles também forem cadastrados como usuários dos Serviços, poderão acessar determinados dados não públicos que você tenha inserido no seu perfil de usuário dos Serviços. Novamente, não controlamos as políticas e práticas de qualquer outro site ou serviço de terceiros.<br/><br/>
              <li>Transferências de negócios: Podemos optar por comprar ou vender ativos e podemos compartilhar e/ou transferir os dados dos clientes em relação à avaliação dessas transações e na entrada em vigor de tais transações. Também, se nós (ou nossos ativos) formos adquiridos, ou encerrarmos nossas atividades, entrarmos em processo de falência ou passarmos por alguma outra mudança de controle, os Dados Pessoais podem ser um dos ativos transferidos a terceiros ou adquiridos por estes.</li><br/>
              <li>Proteção da Lyndus e de outros: Reservamo-nos o direito de acessar, ler, preservar e divulgar quaisquer dados que acreditarmos serem necessários para o cumprimento à lei ou ordem judicial; fazer cumprir ou aplicar os nossos Termos de Uso e outros acordos; ou para proteger os direitos, propriedade ou segurança da Lyndus, bem como de nossos funcionários, usuários ou outros.</li><br/>
              A fim de resguardar a sua privacidade e segurança, sua conta é protegida por uma senha. Ao acessar a sua conta através de um site ou serviço de terceiros, você pode ter proteções de acesso adicionais ou diferentes por meio desse site ou serviço de terceiros. Você deve evitar o acesso não autorizado à sua conta e Dados Pessoais por meio da seleção e proteção adequadas da sua senha e/ou outro mecanismo de acesso, bem como limitar o acesso ao seu computador ou dispositivo e navegador ao encerrar sua sessão depois de terminar o acesso à conta.<br/><br/>
              Aplicamos esforços a fim de proteger a privacidade da sua conta e outros Dados Pessoais mantidos em nossos registros, mas, infelizmente, não podemos garantir a segurança completa. A entrada ou uso não autorizado, falha de software ou hardware e outros fatores podem comprometer a segurança dos dados do usuário a qualquer momento. Os servidores Lyndus são hospedados nas instalações de serviços da Cloudevops Tecnologia da Informação CNPJ 26.360.106/0001-90, no Brasil.<br/><br/>
              Ao acessar ou usar os Serviços Lyndus ou fornecer dados para nós, você concorda com o processamento, armazenamento e transferência de dados no Brasil. Durante a transmissão, todos os dados são criptografados.<br/><br/>
              Através de suas configurações da conta, é possível acessar e editar os dados que você nos forneceu. Se desejar exercer qualquer um dos seus direitos sobre os seus dados (para obter um resumo destes, consulte abaixo), e essa opção ainda não estiver disponível nas configurações de conta, entre em contato no e-mail abaixo e trataremos a sua solicitação assim que possível.<br/><br/>
              Os dados que você pode visualizar e atualizar podem mudar conforme houver alterações nos Serviços. Se tiver alguma dúvida sobre como visualizar ou atualizar os dados, ou para solicitar a exclusão dos seus Dados Pessoais que temos arquivados, entre em contato conosco pelo e-mail ajuda@lyndus.com.br. <br/><br/>
              Observe que possuímos e podemos usar dados agregados e anônimos derivados ou incorporados a partir dos seus Dados Pessoais depois que você nos fornecer tais dados, porém, apagaremos quaisquer Dados Pessoais específicos mediante solicitação.<br/><br/>
              Você sempre pode optar por não nos divulgar os dados, mas tenha em mente que alguns dados podem ser necessários para se registrar conosco ou aproveitar alguns dos nossos recursos.<br/><br/>
              Você pode adicionar ou atualizar os dados, conforme explicado acima. <br/><br/>
              Ao atualizar os dados, no entanto, podemos manter uma cópia dos dados não atualizados em nossos registros. Você pode solicitar o cancelamento da sua conta por e-mail (ajuda@lyndus.com.br) ou suporte via chat. Alguns dados podem permanecer em nossos registros depois que você solicitar a exclusão de dados de sua conta na forma descrita acima. Possuímos e podemos usar quaisquer dados agregados derivados ou incorporados a partir dos seus Dados Pessoais depois que você os atualizar ou excluir, mas não em uma forma que possa identificá-lo pessoalmente.<br/><br/>
              Abaixo, resumimos todos os seus direitos no âmbito da Lei Geral de Proteção de Dados (LGPD). Os principais direitos que você tem sobre seus dados conforme disposto na LGPD são:<br/><br/>
              <ul>
                <li>O direito de denunciar a uma autoridade fiscalizadora; e</li>
                <li>O direito de contestar o processamento;</li>
                <li>O direito de exclusão;</li>
                <li>O direito de acesso;</li>
                <li>O direito de retificação;</li>
                <li>O direito de restringir o processamento;</li>
                <li>O direito à portabilidade dos dados;</li>
                <li>O direito de revogar o consentimento.</li>
              </ul>
              Se tiver dúvidas ou preocupações sobre nossas políticas de privacidade, ou sobre como exercer qualquer um dos seus direitos, envie-nos uma mensagem detalhada para ajuda@lyndus.com.br, e vamos tentar resolver essas questões.<br/><br/>
              Versão de Março de 2022.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Politicas