const Privacidade = () => {

  return (
    <div>
      <div className="container-fluid">
        <div className="container privacidade">
          <div className="row">
            <div className="col">
              <h1>Política de Privacidade</h1>
              <br/><br/>
              <p>Na Lyndus levamos a sua privacidade muito a sério. Leia nossa Política de Privacidade a seguir para conhecê-la melhor.<br/><br/>
              Você está no nosso site e lhe desejamos boas vindas ao universo Lyndus. Para navegar aqui basta estar de acordo com a nossa política de privacidade. Entretanto, para utilizar as demais ferramentas da plataforma citadas aqui no site, bem como usufruir de todas as funcionalidades oferecidas no aplicativo, por exemplo, você deverá também aceitar também os nossos Termos e Condições de Uso no momento do teu cadastro na respectiva ferramenta. Os Termos e Condições de Uso estão disponíveis para consulta na página inicial do aplicativo e também nas páginas da Lyndus nas respectivas lojas (Google Play e App Store).<br/><br/>
              Lembre-se que a sua utilização dos Serviços Lyndus será, em todos os momentos, sem prejuízo ao disposto nos Termos e Condições de Uso, que incorpora a presente Política de Privacidade. Quaisquer termos que utilizamos nesta Política sem sua respectiva definição possuem as definições que lhes foram atribuídos nos Termos e Condições de Uso.<br/><br/>
              Você reconhece que aceita as práticas e políticas descritas neste documento, bem como consente que coletemos, usemos, tratemos e compartilhemos os seus dados das maneiras descritas a seguir.<br/><br/>
              A Lyndus é uma plataforma que atua como conectora entre salões de beleza, clínicas de estética, barbearias, spas, academias, estúdios e outros estabelecimentos de beleza ou bem-estar que tenham celebrado um contrato de parceria com a Lyndus (“Beauty Spots” ou “Parceiros”) e indivíduos que desejam adquirir os serviços de beleza oferecidos por tais Parceiros (“Usuários” ou ‘’Você”), a fim de permitir que você os compre e faça uso dos serviços de beleza e bem-estar oferecidos (‘’Serviços’’) pelo Parceiro por meio do aplicativo Lyndus.<br/><br/>
              A Lyndus pertence e é operada pela LYNDUS S/A, CNPJ nº 43.616.904/0001-59, sediada na Rua Padre Anchieta, nº 2348, Sala 1903, bairro Bigorrilho, CEP 80-730-001, Curitiba-PR, Brasil ("Lyndus", "Nós", "nos" e equivalentes). Esta Política de Privacidade abrange o tratamento de dados pessoais ("Dados Pessoais") que coletamos quando você estiver acessando ou utilizando nossos Serviços (seja individualmente ou por meio do seu empregador), e se aplica onde atuamos como um controlador de dados – nos casos em que determinamos como e por que os seus Dados Pessoais estão sendo tratados. A presente Política não se aplica a práticas das empresas que não possuímos ou controlamos ou às pessoas que não gerenciamos, na medida em que não compartilhamos seus Dados Pessoais com tais empresas ou pessoas.<br/><br/>
              Se tiver quaisquer perguntas, comentários ou preocupações sobre esta Política de Privacidade, entre em contato conosco: ajuda@lyndus.com.br.<br/><br/>
              Coletamos vários tipos de Dados Pessoais de nossos usuários, conforme explicado em mais detalhes abaixo, e usamos esses Dados Pessoais internamente em conexão com os nossos serviços, incluindo personalizar, fornecer e melhorar os nossos serviços, para que você possa configurar um perfil e conta de usuário, para que possamos entrar em contato com você e a fim de permitir que outros usuários entrem em contato com você, bem como visando atender suas solicitações relativas a determinados produtos e serviços e analisar como você usa os Serviços.<br/><br/>
              Em determinadas circunstâncias, também podemos compartilhar alguns Dados Pessoais com terceiros, mas somente como descrito abaixo.<br/><br/>
              Conforme observado nos Termos de uso, não coletamos ou solicitamos intencionalmente Dados Pessoais de pessoas menores de 16 anos. Se tiver menos de 16 anos, não se registre nos Serviços nem envie quaisquer Dados Pessoais para nós. Se tomarmos conhecimento de que coletamos Dados Pessoais de uma pessoa com menos de 16 anos, eliminaremos esses dados o mais rápido quanto possível. Se acreditar que uma pessoa menor de 16 anos pode ter nos fornecido seus Dados Pessoais, entre em contato conosco em ajuda@lyndus.com.br.<br/><br/>
              Estamos constantemente buscando melhorar os nossos Serviços, assim podemos precisar alterar esta Política de Privacidade eventualmente, entretanto, vamos alertá-lo sobre essas mudanças, colocando um aviso no site da Lyndus (https://www.lyndus.com.br), enviando-lhe um e-mail e/ou por outros meios. Observe que se tiver optado por não receber nossos e-mails de aviso legal (ou se ainda não nos forneceu seu endereço de e-mail), os avisos legais ainda regerão o seu uso dos Serviços, e você ainda será responsável por os ler e entender. Se decidir usar os Serviços após a publicação de quaisquer alterações da Política de Privacidade, você deverá aceitar as alterações consoante suas condições.<br/><br/>
              A Lyndus possui um produto corporativo chamado LyndusFazBem, pelo qual as empresas poderão conceder créditos para seus colaboradores utilizarem dentro da plataforma Lyndus e consumir em serviços prestados pelos Beauty Spots cadastrados. Nesse caso, a Lyndus coleta os dados que a empresa fornecedora do benefício para seus colaboradores nos ceder, visto que a fim de prestar os nossos Serviços, podemos receber e armazenar Dados Pessoais sobre você, os quais podem ser compartilhados conosco por seu empregador. Esses dados envolvem o seu nome completo, seu CPF, eventualmente o endereço de e-mail corporativo e, em alguns casos, o número de identificação do funcionário.<br/><br/>
              Podemos usar esses dados para contactá-lo, fazer referências cruzadas com outros Dados Pessoais que podemos manter sobre você em conformidade com esta Política, bem como compartilhar esses dados com o Beauty Spot que você escolher e com nossos parceiros comerciais, conforme previsto na presente Política.<br/><br/>
              Por meio deste, você reconhece que podemos receber Dados Pessoais sobre você do seu empregador e concorda com o nosso tratamento e compartilhamento desses dados nos termos desta Política. A base jurídica deste processamento é o consentimento que você concede por meio desta Política.<br/><br/>
              A Lyndus também coleta, recebe e armazena quaisquer dados que você nos forneça conscientemente. Especificamente, por meio do processo de registro de conta e/ou por meio das suas configurações de conta, coletamos seu nome completo, endereço de e-mail, número de telefone, dados de cartão de crédito/débito, dados da conta de débito, credenciais de conta de terceiros (por exemplo, suas credenciais de acesso ao Facebook/Instagram/WhatsApp), data de nascimento, endereço, gênero, sites pessoais e categorias favoritas. Ao fornecer acesso aos Serviços por meio de um site ou serviços de terceiros (como o Facebook/Instagram/WhatsApp), você entende que determinados conteúdos e/ou dados destas contas ("Dados da Conta de Terceiros") podem ser transmitidos para a sua conta conosco e que os Dados da Conta de Terceiros transmitidos aos nossos Serviços são cobertos pela presente Política de Privacidade. Determinados dados podem ser necessários para se registrar conosco ou para aproveitar alguns de nossos recursos.<br/><br/>
              Podemos nos comunicar com você se tiver nos fornecido os meios para isso. Por exemplo, se você tiver nos fornecido o seu endereço de e-mail, podemos enviar ofertas por e-mails promocionais em nome de outras empresas ou um e-mail sobre o seu uso dos Serviços. Ao nos fornecer o seu número de telefone celular, endereço de e-mail ou credenciais de conta do Facebook, você confirma que quer que a Lyndus lhe envie os dados que achar que podem ser de seu interesse, incluindo, sem limitação, promoções e atualizações sobre os Parceiros Lyndus, e você concorda em receber e-mails, SMS, notificações push e mensagens nas redes sociais. Se não quiser receber nossas comunicações, indique suas preferências e, para isso, clique no link de descadastramento que aparecerá em todos os e-mails ou entre em contato pelo e-mail relacionamento@lyndus.com.br. A Lyndus usará todos os esforços razoáveis para realizar o seu descadastramento dentro de 72 horas a partir da data de recepção da solicitação.<br/><br/>
              Podemos usar esses dados para contactá-lo, fazer referências cruzadas com outros Dados Pessoais que podemos manter sobre você em conformidade com esta Política, bem como compartilhar esses dados com o ESTABELECIMENTO que você escolher e com nossos parceiros comerciais, conforme previsto na presente Política.<br/><br/>
              Também podemos compartilhar seus dados com parceiros de agendamento com os quais você escolheu agendar categorias, mas isso somente acontecerá se você concordar, em cada momento, ao agendar uma categoria.<br/><br/>
              Além desses, alguns dados são coletados automaticamente sempre que você interagir com os nossos Serviços, por meio do nosso site ou via um aplicativo móvel. Automaticamente receberemos e registraremos dados em nosso servidor a partir do seu navegador ou dispositivo, os quais podem incluir seu endereço IP, dados de geolocalização, identificação do dispositivo, dados de "cookie" (veja abaixo), o tipo de navegador e/ou dispositivo utilizado para acessar nossos Serviços, a página ou recurso solicitado e o tempo de acesso.<br/><br/>
              Podemos utilizar estes dados para lhe fornecer uma experiência personalizada, com base em seus padrões de uso, ou para o remarketing, impressão de relatórios, gerenciamento ou outras análises. Também podemos usá-los para melhorar os Serviços – por exemplo, esses dados podem nos dizer com qual frequência os usuários usam um recurso específico dos Serviços e, dessa forma, podemos usar esse conhecimento para melhorar a experiência do usuário.<br/><br/>
              "Cookies" são identificadores que transferimos ao seu navegador ou dispositivo que nos permitem reconhecê-lo, bem como nos informa como e quando as páginas e recursos são visitados em nossos Serviços e por quantas pessoas.<br/><br/>
              Por meio de cookies, podemos coletar dados sobre sua atividade on-line depois que sair dos nossos Serviços. Assim como outros dados de uso que coletamos, esses dados nos permitem melhorar os serviços e personalizar a sua experiência on-line e como de outra forma descrita nesta Política de Privacidade. Atualmente, nossos Serviços não são compatíveis com solicitações de "não rastreamento", o que significa que poderemos coletar dados sobre sua atividade on-line enquanto estiver usando os Serviços.<br/><br/>
              Especificamente, usamos os cookies de acordo com as seguintes finalidades:<br/><br/>
              <ul>
                <li>Autenticação e o status de logon – usamos os cookies para identificá-lo ao abrir o nosso site e para saber se você está conectado ou não ao nosso site;</li>
                <li>Publicidade – usamos os cookies para nos ajudar a identificar seus padrões de uso em nosso site e aplicativo, bem como para nos auxiliar a exibir anúncios que sejam relevantes a você;</li>
              </ul>
              Usamos o Google Analytics para analisar o uso do nosso site e do nosso aplicativo. O Google coleta dados sobre a utilização do site e de aplicativo através de cookies e usa esses dados para criar relatórios sobre a utilização do nosso site e aplicativo.<br/><br/>
              A política de privacidade do Google está disponível em: www.google.com/policies/privacy/, e ao usar o link www.google.com/settings/ads, o usuário pode configurar ou desvincular alguns desses métodos de coleta de dados.<br/><br/>
              Além disso, é possível alterar suas preferências no navegador ou dispositivo, a fim de impedir ou limitar a aceitação de cookies no dispositivo, entretanto, essa ação pode impedi-lo de desfrutar de alguns dos nossos recursos. Novamente, esta Política de Privacidade não abrange a utilização de cookies por quaisquer terceiros, e não somos responsáveis por suas práticas e políticas de privacidade. Esteja ciente de que os cookies colocados por terceiros podem continuar a rastrear suas atividades on-line, mesmo após ter deixado nossos Serviços, e esses terceiros podem não cumprir a solicitação de "não rastreamento" que você pode ter definido usando o navegador ou dispositivo.<br/><br/>
              Não arrendamos, vendemos ou transferimos o seu formulário de Dados Pessoais a ninguém, exceto conforme expressamente previsto abaixo. Podemos compartilhar seus Dados Pessoais com terceiros, conforme descrito a seguir:<br/><br/>
              <li>Beauty Spots: Podemos compartilhar alguns dos seus Dados Pessoais com esses para que elas possam inscrevê-lo em seus sistemas e a fim de permitir que você participe dos serviços. Os únicos dados que compartilhamos com os Beauty Spots são o seu nome completo, número de telefone, endereço de e-mail e informações de passe diário (check-in) geradas pelo nosso sistema.</li><br/>
              Podemos remover a identificação pessoal dos seus Dados Pessoais para que você não seja identificado como uma pessoa e fornecer os dados aos Beauty Spots ou a um cliente corporativo (ou seja, o seu empregador). Além disso, podemos fornecer dados de uso agregado aos Salões/Barbearias ou clientes corporativos (ou permitir que parceiros ou clientes corporativos coletem esses dados de você), os quais podem usar esses dados para entender quantas vezes e de que maneira os usuários usam nossos Serviços, de forma que eles também possam proporcionar aos usuários uma experiência ideal.<br/><br/>
              No entanto, nunca divulgaremos o uso agregado ou dados com a identificação removida a um Beauty Spot ou cliente corporativo de forma que isso possa identificá-lo como um indivíduo, direta ou indiretamente. A Lyndus armazena dados que são usados na forma de estatísticas agregadas e genéricas ou relatórios, a fim de obter uma melhor compreensão dos perfis de usuário com o objetivo de melhorar os produtos e serviços oferecidos pela Lyndus.<br/><br/>
              Podemos, eventualmente, permitir que anunciantes e/ou parceiros comerciais ("Anunciantes") escolham os dados demográficos dos usuários que verão seus anúncios e/ou ofertas promocionais, e você concorda que podemos fornecer quaisquer dados coletados de forma não pessoalmente identificável a um Anunciante, para que este selecione o público adequado para os anúncios e/ou ofertas. Por exemplo, podemos usar o fato de que você estar localizado em Curitiba para mostrar anúncios ou ofertas das empresas de Curitiba, mas não diremos a tais empresas quem é você. Ou podemos permitir que os Anunciantes exibam seus anúncios aos usuários com padrões de uso semelhante ao seu, mas não divulgaremos dados de uso aos Anunciantes, exceto na forma agregada, bem como não os divulgaremos de uma forma que possa identificá-lo pessoalmente. <br/><br/>
              Vale observar que se um Anunciante nos solicitar para mostrar um anúncio a um determinado público ou segmento de público, e você responder a esse anúncio, o Anunciante pode concluir que você se encaixa na descrição do público-alvo que ele almejava alcançar.<br/><br/>
              Usamos ferramentas como Google Tag Manager, Facebook, Instagram, WhatsApp e LinkedIn para nos comunicar com os usuários, com base nos dados coletados por esses anunciantes e também para nos comunicar com os usuários com base nos dados que coletamos em nosso site e ou via um aplicativo móvel.<br/><br/>
              <li>Empresas Afiliadas: Em determinadas situações, as empresas ou sites de terceiros que são filiados, eventualmente, vendem ou fornecem produtos ou serviços a você por meio de ou em conexão com os Serviços (individualmente ou em conjunto conosco). É possível reconhecer quando uma empresa afiliada está associada a um serviço ou transação, e vamos compartilhar os seus Dados Pessoais com essa empresa afiliada apenas na medida em que estes estiverem relacionados com tal transação ou serviço. Não temos controle sobre as políticas e práticas de empresas ou sites de terceiros quanto à privacidade, ou qualquer outro fator. Assim, se optar por tomar parte em qualquer transação ou serviço relacionado com uma empresa ou site afiliado, reveja todas as políticas dessas empresas ou sites.</li><br/>
              <li>Nossos Agentes: Utilizamos outras empresas e pessoas para executar tarefas em nosso nome e precisamos compartilhar seus dados com eles para lhe fornecer produtos ou serviços; por exemplo, além da plataforma própria, também utilizamos uma empresa de processamento de pagamentos que é responsável por receber e processar suas transações de cartão de crédito em nosso nome. A menos que tenhamos comunicado de outra forma, nossos agentes não têm qualquer direito de utilizar os Dados Pessoais compartilhados com eles além do que for necessário para nos ajudar.</li><br/>
              <li>Inscrições e perfis de usuário: Determinados dados de conta, incluindo seu nome, localização e qualquer conteúdo de vídeo ou imagem que um usuário carregar nos Serviços, podem ser exibidos a outros usuários para facilitar a interação do usuário dentro dos Serviços ou atender uma solicitação relativa aos nossos Serviços. Lembre-se que qualquer conteúdo que enviar ao seu perfil de usuário público, juntamente com quaisquer dados pessoais ou conteúdo que voluntariamente divulgar on-line de alguma maneira, que outros usuários poderão visualizar (em fóruns de discussão, mensagens, áreas de bate-papo etc.), tornam-se publicamente disponíveis, podendo ser coletados e utilizados por qualquer pessoa. </li><br/>
              O seu nome de usuário também pode ser exibido a outros usuários, se e quando você enviar mensagens ou comentários, bem como ao carregar imagens ou vídeos através dos Serviços, e outros usuários podem entrar em contato com você por meio de mensagens e comentários. Além disso, ao se inscrever nos Serviços através de um serviço ou site de rede social de terceiros, a sua lista de "amigos" desse site ou serviço pode ser automaticamente importada aos Serviços, e tais "amigos", se eles também forem cadastrados como usuários dos Serviços, poderão acessar determinados dados não públicos que você tenha inserido no seu perfil de usuário dos Serviços. Novamente, não controlamos as políticas e práticas de qualquer outro site ou serviço de terceiros.<br/><br/>
              <li>Transferências de negócios: Podemos optar por comprar ou vender ativos e podemos compartilhar e/ou transferir os dados dos clientes em relação à avaliação dessas transações e na entrada em vigor de tais transações. Também, se nós (ou nossos ativos) formos adquiridos, ou encerrarmos nossas atividades, entrarmos em processo de falência ou passarmos por alguma outra mudança de controle, os Dados Pessoais podem ser um dos ativos transferidos a terceiros ou adquiridos por estes.</li><br/>
              <li>Proteção da Lyndus e de outros: Reservamo-nos o direito de acessar, ler, preservar e divulgar quaisquer dados que acreditarmos serem necessários para o cumprimento à lei ou ordem judicial; fazer cumprir ou aplicar os nossos Termos de Uso e outros acordos; ou para proteger os direitos, propriedade ou segurança da Lyndus, bem como de nossos funcionários, usuários ou outros.</li><br/>
              A fim de resguardar a sua privacidade e segurança, sua conta é protegida por uma senha. Ao acessar a sua conta através de um site ou serviço de terceiros, você pode ter proteções de acesso adicionais ou diferentes por meio desse site ou serviço de terceiros. Você deve evitar o acesso não autorizado à sua conta e Dados Pessoais por meio da seleção e proteção adequadas da sua senha e/ou outro mecanismo de acesso, bem como limitar o acesso ao seu computador ou dispositivo e navegador ao encerrar sua sessão depois de terminar o acesso à conta.<br/><br/>
              Aplicamos esforços a fim de proteger a privacidade da sua conta e outros Dados Pessoais mantidos em nossos registros, mas, infelizmente, não podemos garantir a segurança completa. A entrada ou uso não autorizado, falha de software ou hardware e outros fatores podem comprometer a segurança dos dados do usuário a qualquer momento. Os servidores Lyndus são hospedados nas instalações de serviços da Cloudevops Tecnologia da Informação CNPJ 26.360.106/0001-90, no Brasil.<br/><br/>
              Ao acessar ou usar os Serviços Lyndus ou fornecer dados para nós, você concorda com o processamento, armazenamento e transferência de dados no Brasil. Durante a transmissão, todos os dados são criptografados.<br/><br/>
              Através de suas configurações da conta, é possível acessar e editar os dados que você nos forneceu. Se desejar exercer qualquer um dos seus direitos sobre os seus dados (para obter um resumo destes, consulte abaixo), e essa opção ainda não estiver disponível nas configurações de conta, entre em contato no e-mail abaixo e trataremos a sua solicitação assim que possível.<br/><br/>
              Os dados que você pode visualizar e atualizar podem mudar conforme houver alterações nos Serviços. Se tiver alguma dúvida sobre como visualizar ou atualizar os dados, ou para solicitar a exclusão dos seus Dados Pessoais que temos arquivados, entre em contato conosco pelo e-mail ajuda@lyndus.com.br.<br/><br/>
              Observe que possuímos e podemos usar dados agregados e anônimos derivados ou incorporados a partir dos seus Dados Pessoais depois que você nos fornecer tais dados, porém, apagaremos quaisquer Dados Pessoais específicos mediante solicitação.<br/><br/>
              Você sempre pode optar por não nos divulgar os dados, mas tenha em mente que alguns dados podem ser necessários para se registrar conosco ou aproveitar alguns dos nossos recursos.<br/><br/>
              Você pode adicionar ou atualizar os dados, conforme explicado acima. <br/><br/>
              Ao atualizar os dados, no entanto, podemos manter uma cópia dos dados não atualizados em nossos registros. Você pode solicitar o cancelamento da sua conta por e-mail (ajuda@lyndus.com.br) ou suporte via chat. Alguns dados podem permanecer em nossos registros depois que você solicitar a exclusão de dados de sua conta na forma descrita acima. Possuímos e podemos usar quaisquer dados agregados derivados ou incorporados a partir dos seus Dados Pessoais depois que você os atualizar ou excluir, mas não em uma forma que possa identificá-lo pessoalmente.<br/><br/>
              Abaixo, resumimos todos os seus direitos no âmbito da Lei Geral de Proteção de Dados (LGPD). Os principais direitos que você tem sobre seus dados conforme disposto na LGPD são:<br/><br/>
              <ul>
                <li>O direito de denunciar a uma autoridade fiscalizadora; e</li>
                <li>O direito de contestar o processamento;</li>
                <li>O direito de exclusão;</li>
                <li>O direito de acesso;</li>
                <li>O direito de retificação;</li>
                <li>O direito de restringir o processamento;</li>
                <li>O direito à portabilidade dos dados;</li>
                <li>O direito de revogar o consentimento.</li>
              </ul>
              <h2>Política de Cookies</h2>
              <br/>
              A presente Política de Cookies é um documento complementar à Política de Privacidade da Lyndus. Aqui, você encontrará informações objetivas e claras sobre o que são Cookies, os Cookies utilizados em nossas aplicações, qual papel desempenham e como configurá-los.<br/><br/>
              1. O que são Cookies?<br/><br/>
              Cookies são pequenos arquivos de texto ou fragmentos de informação que são baixados em seu computador, smartphone ou qualquer outro dispositivo com acesso à internet quando você visita nossa aplicação.<br/><br/>
              Eles contêm informações sobre a sua navegação em nossas páginas e retêm apenas informações relacionadas a suas preferências.<br/><br/>
              Assim, essa página consegue armazenar e recuperar os dados sobre os seus hábitos de navegação, de forma a melhorar a experiência de uso, por exemplo. É importante frisar que eles não contêm informações pessoais específicas, como dados sensíveis ou bancários.<br/><br/>
              O seu navegador armazena os cookies no disco rígido, mas ocupam um espaço de memória mínimo, que não afetam o desempenho do seu computador. A maioria das informações são apagadas logo ao encerrar a sessão, como você verá no próximo tópico.<br/><br/>
              1.1. Tipos de Cookies<br/><br/>
              Os cookies, quanto a seus proprietários, podem ser:<br/><br/>
              Cookies proprietários: são cookies definidos por nós ou por terceiros em nosso nome;<br/><br/>
              Cookies de terceiros: são cookies definidos por terceiros confiáveis em nossa aplicação.<br/><br/>
              Os cookies, quanto ao seu tempo de vida, podem ser:<br/><br/>
              Cookies de sessão ou temporários: são cookies que expiram assim que você fecha o seu navegador, encerrando a sessão;<br/><br/>
              Cookies persistentes ou permanentes: são cookies que permanecem no seu dispositivo durante um período determinado ou até que você os exclua.<br/><br/>
              Os cookies, quanto a sua finalidade, podem ser:<br/><br/>
              Cookies necessários: são cookies essenciais que possibilitam a navegação em nossas aplicações e o acesso a todos os recursos; se estes, nossos serviços podem apresentar mau desempenho ou não funcionar;<br/><br/>
              Cookies de desempenho: são cookies que otimizam a forma que nossas aplicações funcionam, coletando informações anônimas sobre as páginas acessadas;<br/><br/>
              Cookies de funcionalidade: são cookies que memorizam suas preferências e escolhas (como seu nome de usuário);<br/><br/>
              Cookies de publicidade: são cookies que direcionam anúncios em função dos seus interesses e limitam a quantidade de vezes que o anúncio aparece.<br/><br/>
              2. Por que usamos Cookies?<br/><br/>
              A Lyndus utiliza Cookies para fornecer a melhor experiência de uso, tornando nossas aplicações mais fáceis e personalizadas, tendo por base suas escolhas e comportamento de navegação.<br/><br/>
              Assim, buscamos entender como você utiliza nossas aplicações e ajustar o conteúdo para torná-lo mais relevante para você, além de lembrar de suas preferências.<br/><br/>
              Os Cookies participam deste processo porquanto armazenam, leem e executam os dados necessários para cumprir com o nosso objetivo.<br/><br/>
              3. Gerenciamento dos Cookies<br/><br/>
              A instalação dos cookies está sujeita ao seu consentimento. Apesar da maioria dos navegadores estarem inicialmente configurados para aceitar cookies de forma automática, você pode rever suas permissões a qualquer tempo, de forma a bloqueá-los, aceitá-los ou ativar notificações para quando alguns cookies forem enviados ao seu dispositivo.<br/><br/>
              Atualmente, na primeira vez que você acessar nossas aplicações, será requerida a sua concordância com a instalação destes. Apenas após a sua aceitação eles serão ativados.<br/><br/>
              Para tanto, utilizamos um sistema de aviso na página inicial da Lyndus. Dessa maneira, não apenas solicitamos sua concordância, mas também informamos que a navegação continuada em nossos sites será entendida como consentimento.<br/><br/>
              Como já dito, você pode, a qualquer tempo e sem nenhum custo, alterar as permissões, bloquear ou recusar os Cookies. Você também pode configurá-los caso a caso. Todavia, a revogação do consentimento de determinados Cookies pode inviabilizar o funcionamento correto de alguns recursos da plataforma.<br/><br/>
              Para gerenciar os cookies do seu navegador, basta fazê-lo diretamente nas configurações do navegador, na área de gestão de Cookies.<br/><br/>
              Você pode acessar tutoriais sobre o tema diretamente nos links abaixo:<br/><br/>
              Se você usa o <a href="https://support.microsoft.com/pt-br/help/17442/windows-internet-explorer-delete-manage-cookies" target="_blank">Internet Explorer</a>.<br/>
              Se você usa o <a href="https://support.mozilla.org/pt-BR/kb/gerencie-configuracoes-de-armazenamento-local-de-s" target="_blank">Firefox</a>.<br/>
              Se você usa o <a href="https://support.apple.com/pt-br/guide/safari/sfri11471/mac" target="_blank">Safari</a>.<br/>
              Se você usa o <a href="https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&oco=1&hl=pt-BR" target="_blank">Google Chrome</a>.<br/>
              Se você usa o <a href="https://support.microsoft.com/pt-br/help/4027947/microsoft-edge-delete-cookies" target="_blank">Microsoft Edge</a>.<br/>
              Se você usa o <a href="https://help.opera.com/en/latest/web-preferences/#cookies" target="_blank">Opera</a>.<br/><br/>
              4. Disposições Finais<br/><br/>
              Para a Lyndus, a privacidade e confiança são fundamentais para a nossa relação com você. Estamos sempre nos atualizando para manter os mais altos padrões de segurança.<br/><br/>
              Assim, reservamo-nos o direito de alterar esta Política de Cookies a qualquer tempo. As mudanças entrarão em vigor logo após a publicação, e você será avisado.<br/><br/>
              Ao continuar a navegação nas nossas aplicações após essa mudança se tornar eficaz, você concorda com elas. Aconselhamos que você sempre verifique esta Política, bem como a nossa Política de Privacidade.<br/><br/>
              Se tiver dúvidas ou preocupações sobre nossas políticas de privacidade, ou sobre como exercer qualquer um dos seus direitos, envie-nos uma mensagem detalhada para ajuda@lyndus.com.br e vamos tentar resolver essas questões.<br/><br/>
              Versão de Março de 2022.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Privacidade